# Generated by Django 4.2.2 on 2023-06-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('email', models.CharField(max_length=124)),
                ('phone', models.CharField(max_length=124)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
